#!/usr/bin/env bash
#
# Cuts a release: signed tag, both remotes, GitHub Release, changelog.
#
#   ./scripts/release.sh 2.19.5              # opens $EDITOR for the notes
#   ./scripts/release.sh 2.19.5 -F notes.md
#
# Assumes the version bump is already committed — that stays a separate
# commit by convention, and this checks the two agree rather than editing
# project.yml itself.
#
# The tag message is the single source of truth. This script writes it
# once and then publishes it three ways: the tag, the GitHub Release, and
# CHANGELOG.md. Nothing is written twice, so nothing can drift.
#
# Local rather than CI on purpose: the tag is GPG-signed off a smartcard,
# which lives on this machine. A GitHub Action could create the Release
# on tag push, but it cannot sign, and it would be this repo's first CI
# surface for the sake of one keystroke.
#
# Releases carry NO artifacts. An iOS/watchOS app cannot be distributed
# outside the App Store or TestFlight, so there is nothing to attach and
# attaching something would mislead.

set -euo pipefail
cd "$(dirname "$0")/.."

VERSION=${1:?usage: release.sh <version> [-F notes-file]   e.g. release.sh 2.19.5}
shift
TAG="v$VERSION"
REPO="https://github.com/ecliptik/onigiri"

NOTES_FILE=""
if [ "${1:-}" = "-F" ]; then
  NOTES_FILE=${2:?-F needs a file}
fi

die() { printf '✗ %s\n' "$1" >&2; exit 1; }

# ---- refuse to release something we cannot describe ------------------

[ -n "$(git status --porcelain)" ] && die "working tree is dirty — commit or stash first"

branch=$(git rev-parse --abbrev-ref HEAD)
[ "$branch" = "main" ] || die "on '$branch', not main"

declared=$(sed -n 's/^ *MARKETING_VERSION: *"\(.*\)"/\1/p' project.yml)
[ "$declared" = "$VERSION" ] \
  || die "project.yml says MARKETING_VERSION $declared, not $VERSION — bump and commit it first"

git rev-parse -q --verify "refs/tags/$TAG" >/dev/null \
  && die "$TAG already exists locally"
[ -z "$(git ls-remote --tags origin "refs/tags/$TAG")" ] \
  || die "$TAG already exists on a remote"

command -v gh >/dev/null || die "gh is not installed"
gh auth status >/dev/null 2>&1 || die "gh is not authenticated"

# ---- the notes -------------------------------------------------------

tmp=$(mktemp -t onigiri-release)
trap 'rm -f "$tmp"' EXIT

if [ -n "$NOTES_FILE" ]; then
  cat "$NOTES_FILE" > "$tmp"
else
  # A release with no notes should be awkward to produce, so the
  # template starts empty below the subject and the editor must be used.
  {
    echo "$TAG — "
    echo
    echo "# The first line is the release title, shown on the tag, the GitHub"
    echo "# Release, and in CHANGELOG.md. Lines starting with # are dropped."
    echo "#"
    echo "# Lead with what a reader would NOTICE, then explain the cause —"
    echo "# the house style, and the reason these read well. Markdown renders"
    echo "# on the Release page; four-space-indented blocks become code."
  } > "$tmp"
  "${EDITOR:-vi}" "$tmp"
fi

grep -qv '^#' "$tmp" || die "no notes written — aborting"

# ---- tag, push, publish ----------------------------------------------

git tag -s "$TAG" -F "$tmp" --cleanup=strip
echo "→ signed $TAG"

git push origin main
git push origin "$TAG"
echo "→ pushed to both remotes"

prev=$(git describe --tags --abbrev=0 "$TAG^" 2>/dev/null || true)
{
  ./scripts/tag-notes.sh "$TAG"
  if [ -n "$prev" ]; then
    echo
    echo "**Full changelog**: [$prev...$TAG]($REPO/compare/$prev...$TAG)"
  fi
  echo
  echo "_Notes only — an iOS/watchOS app ships through the App Store, so there are no downloadable artifacts._"
} | gh release create "$TAG" --verify-tag \
      --title "$(git tag -l --format='%(contents:subject)' "$TAG")" \
      --notes-file -

# ---- changelog -------------------------------------------------------
#
# Regenerated AFTER the tag exists, so this commit trails the tag by one.
# main always carries the complete changelog; the tagged tree is one
# commit behind on that file alone, which is inherent to generating it
# from tags and is not worth a pre-tag special case.

./scripts/generate-changelog.sh
if ! git diff --quiet CHANGELOG.md; then
  git commit -q -m "Changelog through $TAG

Regenerated by scripts/generate-changelog.sh — the tag messages are the
source of truth, this file is the offline and Forgejo-side copy.

Co-Authored-By: Claude Opus 5 (1M context) <noreply@anthropic.com>" CHANGELOG.md
  git push -q origin main
  echo "→ changelog updated"
fi

echo "✓ $TAG released — $REPO/releases/tag/$TAG"
